name: Main
jobs:
send-message:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3

    # Define secret variables for bot_token and chat_id
  - name: Set secret variables
    run: |
      echo "::add-mask::${{ secrets.BOT_TOKEN }}"
      echo "::add-mask::${{ secrets.CHAT_ID }}"
  
    # Use curl to send the message
  - name: Send message to Telegram group
    run: |
      curl -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.CHAT_ID }} \
        -d text="Haha"
